import { Type, type Static } from "@sinclair/typebox";

export const chatEntrySchema = Type.Object(
  {
    chatId: Type.Union([Type.String(), Type.Number()], {
      description: "Telegram chat ID or username (e.g. -1001234567890 or @mychannel)",
    }),
    label: Type.Optional(Type.String({ description: "Human-readable label for logs" })),
  },
  { additionalProperties: false },
);

export const pluginConfigSchema = Type.Object(
  {
    apiId: Type.Number({ description: "Telegram API ID from https://my.telegram.org" }),
    apiHash: Type.String({ description: "Telegram API Hash from https://my.telegram.org" }),
    sessionString: Type.Optional(
      Type.String({
        description:
          "Session string generated by `openclaw telegram-chat-summary setup`. Required to connect.",
      }),
    ),
    chats: Type.Optional(Type.Array(chatEntrySchema)),
    schedulerEnabled: Type.Optional(
      Type.Boolean({ description: "Whether the background summary scheduler is enabled (default: true)" }),
    ),
    scheduleMinutes: Type.Optional(
      Type.Number({ description: "How often to summarize all chats, in minutes (default: 60)" }),
    ),
    language: Type.Optional(Type.String({ description: "Summary language (default: zh-CN)" })),
    maxMessagesPerFetch: Type.Optional(
      Type.Number({ description: "Max messages to fetch per chat per run (default: 500)" }),
    ),
    botToken: Type.Optional(
      Type.String({ description: "Send all summaries via this bot token instead of user account" }),
    ),
    alertChatId: Type.Optional(
      Type.Union([Type.String(), Type.Number()], {
        description: "Personal chat ID to receive bot summaries (your Telegram user ID)",
      }),
    ),
    summaryPrompt: Type.Optional(
      Type.String({
        description:
          "Custom prompt template. Placeholders: {messages} {language} {timeRange} {chatTitle}",
      }),
    ),
    proxy: Type.Optional(
      Type.Object(
        {
          host: Type.String(),
          port: Type.Number(),
          socksType: Type.Optional(Type.Union([Type.Literal(4), Type.Literal(5)])),
          username: Type.Optional(Type.String()),
          password: Type.Optional(Type.String()),
        },
        { additionalProperties: false, description: "SOCKS proxy for MTProto connection" },
      ),
    ),
  },
  { additionalProperties: false },
);

export type PluginConfig = Static<typeof pluginConfigSchema>;
export type ChatEntry = Static<typeof chatEntrySchema>;

export const DEFAULT_SCHEDULER_ENABLED = true;
export const DEFAULT_SCHEDULE_MINUTES = 60;
export const DEFAULT_LOOKBACK_MINUTES = 60;
export const DEFAULT_MAX_MESSAGES = 500;
export const DEFAULT_LANGUAGE = "zh-CN";
export const DEFAULT_SUMMARY_PROMPT = `请用{language}对以下 Telegram 聊天记录进行简洁摘要。
摘要涵盖主要话题、重要决定和关键信息，忽略无意义的闲聊和重复内容。

对话：{chatTitle}
时间范围：{timeRange}

聊天记录：
{messages}

请提供结构清晰的摘要，使用要点形式。`;

export function isSchedulerEnabled(cfg: PluginConfig): boolean {
  return cfg.schedulerEnabled ?? DEFAULT_SCHEDULER_ENABLED;
}
